# Generated by Django 4.2.1 on 2023-06-28 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cartapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='cid',
            new_name='cart_id',
        ),
    ]
